### ISSUE TITLE
Getting error cannot find module './utils'

### ISSUE THREAD

**Issue by DarkSide666** [autosuite/autocommit#7]
Getting this error now.

```
/usr/bin/docker exec  6b3c5a6495cf71be5299f6397d4b24f470e68e9a5dae4abd4feef70674a35469 sh -c "cat /etc/*release | grep ^ID"
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module './utils'
Require stack:
- /__w/_actions/autosuite/autocommit/master/node_modules/@actions/core/lib/command.js
- /__w/_actions/autosuite/autocommit/master/node_modules/@actions/core/lib/core.js
- /__w/_actions/autosuite/autocommit/master/dist/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/__w/_actions/autosuite/autocommit/master/node_modules/@actions/core/lib/command.js:11:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/__w/_actions/autosuite/autocommit/master/node_modules/@actions/core/lib/command.js',
    '/__w/_actions/autosuite/autocommit/master/node_modules/@actions/core/lib/core.js',
    '/__w/_actions/autosuite/autocommit/master/dist/main.js'
  ]
}
```

**Comment by paced** [comment]
Thanks for the bug report. Is there a version that works other than the `main` version?

**Comment by DarkSide666** [comment]
Well, `autosuite/autocommit` do not have a single released version and only 2 branches in github. So nothing worked.
Previously we was using `teaminkling/autocommit@master` and that also worked fine about month or a bit more ago.
Now it redirects here and this one have this issue. I guess something is not compiled correctly, but had no time left to dive more into this.

As result I switched to `stefanzweifel/git-auto-commit-action@v4`. That works fine.

**Comment by paced** [comment]
I've actually taken a look at that a few hours ago and I'm considering just pointing this repo to that one. I rebase and refactor these projects too frequently for them to be considered stable, unfortunately, which would be annoying to anybody trying to use them.

Cheers for the link to the working repo, glad it works now.
